In [25]:
import pandas as pd
import numpy as np

# Creating DataFrame with missing values

data = {
    "Name": ["Sam", "Ram", "Shyam", None],
    "Age": [20, np.nan, 30, 25],
    "Salary": [30000, 40000, np.nan, np.nan]
}

df = pd.DataFrame(data)

print(df)

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN
3   None  25.0      NaN

In [26]:
# Check missing values 

df.isna()

    Name    Age  Salary
0  False  False   False
1  False   True   False
2  False  False    True
3   True  False    True

In [27]:
df.isna().sum()

Name      1
Age       1
Salary    2
dtype: int64

In [28]:
df.isna().any() # any() -> proivde how many null values in each column

Name      True
Age       True
Salary    True
dtype: bool

In [29]:
df

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN
3   None  25.0      NaN

In [30]:
# Removing Missing Dataabs -> works on row basis

df.dropna()   # all the rows are drop which have null values

  Name   Age   Salary
0  Sam  20.0  30000.0

In [31]:
df

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN
3   None  25.0      NaN

In [32]:
df.dropna(thresh=2)   # thresh = 2 -> means in row minimum two non zero element are there

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN

In [34]:
# Fill missing values 

df

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN
3   None  25.0      NaN

In [35]:
df.fillna(0)

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   0.0  40000.0
2  Shyam  30.0      0.0
3      0  25.0      0.0

In [37]:
values = {"Name":"ZZZ","Age":000,"Salary":"XXXX"}
df.fillna(value=values)   # value -> is a keyword

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   0.0  40000.0
2  Shyam  30.0     XXXX
3    ZZZ  25.0     XXXX

In [38]:
df

    Name   Age   Salary
0    Sam  20.0  30000.0
1    Ram   NaN  40000.0
2  Shyam  30.0      NaN
3   None  25.0      NaN

In [45]:
# Fill values using mean of that columnabs

df.fillna(df.mean()) # while taking mean -> data should be in numbers

TypeError: can only concatenate str (not "int") to str

In [44]:
x = df.iloc[:,1:2]
print(x)
x.fillna(x.mean())

    Age
0  20.0
1   NaN
2  30.0
3  25.0

                                                 Age
0                                               20.0
1  <bound method DataFrame.mean of     Age\n0  20...
2                                               30.0
3                                               25.0