In [53]:
import pandas as pd

# Create first DataFrame
df1 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

# Create second DataFrame
df2 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [10000, 20000, 30000]
})

In [54]:
df1

   ID Name
0   1    A
1   2    B
2   3    C

In [55]:
df2

   ID  Salary
0   1   10000
1   2   20000
2   4   30000

In [56]:
# Merge both DataFrames on common column "ID"
# Default = INNER JOIN --> (only matching values kept)
result = pd.merge(df1, df2, on="ID")    # by default -> how = "inner"

# Print result
print("MERGE OUTPUT:")
print(result)

MERGE OUTPUT:
   ID Name  Salary
0   1    A   10000
1   2    B   20000

In [57]:
result = pd.merge(df1, df2, on="ID" , how="outer") # how = "outer" -> take all the id's of both dataset
print("MERGE OUTPUT:")
print(result)

MERGE OUTPUT:
   ID Name   Salary
0   1    A  10000.0
1   2    B  20000.0
2   3    C      NaN
3   4  NaN  30000.0

In [58]:
# Create DataFrames

df3 = pd.DataFrame({
    "A": [1, 2],
    "B": [3, 4]
})

df4 = pd.DataFrame({
    "A": [5, 6],
    "B": [7, 8]
})

In [59]:
df3

   A  B
0  1  3
1  2  4

In [60]:
df4

   A  B
0  5  7
1  6  8

In [61]:
# 🔸 Row-wise concatenation (default axis=0)
# Stacks df2 below df1

row_concat = pd.concat([df1, df2], axis = 0)

print("\nROW CONCAT:")
print(row_concat)

# 🔸 Column-wise concatenation (axis=1)
# Adds df2 as new columns beside df1

col_concat = pd.concat([df1, df2], axis=1)

print("\nCOLUMN CONCAT:")
print(col_concat)

ROW CONCAT:
   ID Name   Salary
0   1    A      NaN
1   2    B      NaN
2   3    C      NaN
0   1  NaN  10000.0
1   2  NaN  20000.0
2   4  NaN  30000.0

COLUMN CONCAT:
   ID Name  ID  Salary
0   1    A   1   10000
1   2    B   2   20000
2   3    C   4   30000

In [62]:
# Create DataFrames
df5 = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["A", "B", "C"]
})

df6 = pd.DataFrame({
    "ID": [1, 2, 4],
    "Salary": [10000, 20000, 30000]
})

In [63]:
df5

   ID Name
0   1    A
1   2    B
2   3    C

In [64]:
df6

   ID  Salary
0   1   10000
1   2   20000
2   4   30000

In [72]:
# Set "ID" as index for both DataFrames

df5.set_index("ID", inplace=True)
df6.set_index("ID", inplace=True)

# Join based on index

# Default = LEFT JOIN (keeps all df5 values)
result = df5.join(df6)    # how -> inner/outer works also in the join 

print("\nJOIN OUTPUT:")
print(result)

KeyError: "None of ['ID'] are in the columns"

In [ ]:
# # MERGE → common column
# pd.merge(df1, df2, on="col")

# # CONCAT → stacking
# pd.concat([df3, df4])

# # JOIN → index
# df5.join(df6)